// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-LSMELtRflufGIpANYas0_G1pqmFJBk',
    appId: '1:342286892657:web:252cc1fa914bd9983965d0',
    messagingSenderId: '342286892657',
    projectId: 'bilsoft-4727b',
    authDomain: 'bilsoft-4727b.firebaseapp.com',
    storageBucket: 'bilsoft-4727b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRDUPFcdBFWhHN2geRx9VN-hBq8d43ck',
    appId: '1:342286892657:android:4d90ee8887ce0bc83965d0',
    messagingSenderId: '342286892657',
    projectId: 'bilsoft-4727b',
    storageBucket: 'bilsoft-4727b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjQkAPa9rFziXwHsNkSFxlD8HkwO4je8',
    appId: '1:342286892657:ios:cefab20ffa3248073965d0',
    messagingSenderId: '342286892657',
    projectId: 'bilsoft-4727b',
    storageBucket: 'bilsoft-4727b.appspot.com',
    iosClientId: '342286892657-mh7eir62e1gvf7hfn8ep744fni9dfhom.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjQkAPa9rFziXwHsNkSFxlD8HkwO4je8',
    appId: '1:342286892657:ios:83e076fb8cb29cc53965d0',
    messagingSenderId: '342286892657',
    projectId: 'bilsoft-4727b',
    storageBucket: 'bilsoft-4727b.appspot.com',
    iosClientId: '342286892657-f09jv5gj4ec2kqb034g1a38ofpaue6i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesTracker.RunnerTests',
  );
}
